# Generated by Django 4.1.3 on 2022-11-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_test_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDo',
        ),
    ]
